-- Albums with enhanced metadata
CREATE TABLE IF NOT EXISTS public.albums (
    id bigint primary key generated always as identity,
    title text not null check (length(title) >= 1),
    slug text unique not null,
    description text,
    cover_url text not null,
    cover_blur_hash text,
    type album_type default 'album',
    genre text,
    release_date date not null,
    total_tracks integer default 0 check (total_tracks >= 0),
    duration_seconds integer default 0 check (duration_seconds >= 0),
    is_premium boolean default false,
    required_tier user_tier default 'grassroot',
    coin_price integer default 0 check (coin_price >= 0),
    play_count integer default 0 check (play_count >= 0),
    like_count integer default 0 check (like_count >= 0),
    download_count integer default 0 check (download_count >= 0),
    is_featured boolean default false,
    is_published boolean default true,
    producer text,
    record_label text,
    copyright_info text,
    explicit_content boolean default false,
    tags text[] default '{}',
    metadata jsonb default '{}',
    created_at timestamp with time zone default now(),
    updated_at timestamp with time zone default now()
);

-- Tracks with comprehensive metadata
CREATE TABLE IF NOT EXISTS public.tracks (
    id bigint primary key generated always as identity,
    album_id bigint references public.albums(id) on delete set null,
    title text not null check (length(title) >= 1),
    slug text unique not null,
    artist text not null default 'Erigga',
    featuring text,
    duration_seconds integer not null check (duration_seconds > 0),
    track_number integer check (track_number > 0),
    disc_number integer default 1 check (disc_number > 0),
    lyrics text,
    cover_url text,
    cover_blur_hash text,
    audio_url text,
    audio_preview_url text,
    waveform_data jsonb,
    is_premium boolean default false,
    required_tier user_tier default 'grassroot',
    coin_price integer default 0 check (coin_price >= 0),
    play_count integer default 0 check (play_count >= 0),
    like_count integer default 0 check (like_count >= 0),
    download_count integer default 0 check (download_count >= 0),
    share_count integer default 0 check (share_count >= 0),
    release_date date not null,
    is_single boolean default false,
    is_featured boolean default false,
    is_published boolean default true,
    genre text,
    mood text,
    tempo integer,
    key_signature text,
    producer text,
    songwriter text,
    explicit_content boolean default false,
    isrc text unique,
    tags text[] default '{}',
    metadata jsonb default '{}',
    created_at timestamp with time zone default now(),
    updated_at timestamp with time zone default now()
);

-- Streaming platform links
CREATE TABLE IF NOT EXISTS public.streaming_links (
    id bigint primary key generated always as identity,
    track_id bigint references public.tracks(id) on delete cascade,
    album_id bigint references public.albums(id) on delete cascade,
    platform text not null check (platform in ('spotify', 'apple_music', 'youtube_music', 'audiomack', 'soundcloud', 'deezer', 'tidal', 'amazon_music')),
    url text not null,
    platform_id text,
    is_verified boolean default false,
    created_at timestamp with time zone default now(),
    check ((track_id is not null) or (album_id is not null)),
    unique(track_id, platform),
    unique(album_id, platform)
);

-- Music videos with enhanced features
CREATE TABLE IF NOT EXISTS public.music_videos (
    id bigint primary key generated always as identity,
    track_id bigint references public.tracks(id) on delete set null,
    title text not null,
    slug text unique not null,
    description text,
    video_url text not null,
    thumbnail_url text not null,
    thumbnail_blur_hash text,
    duration_seconds integer not null check (duration_seconds > 0),
    views integer default 0 check (views >= 0),
    likes integer default 0 check (likes >= 0),
    dislikes integer default 0 check (dislikes >= 0),
    comments_count integer default 0 check (comments_count >= 0),
    is_premium boolean default false,
    required_tier user_tier default 'grassroot',
    coin_price integer default 0 check (coin_price >= 0),
    release_date date not null,
    is_featured boolean default false,
    is_published boolean default true,
    director text,
    producer text,
    location text,
    explicit_content boolean default false,
    quality text default 'HD' check (quality in ('SD', 'HD', '4K')),
    tags text[] default '{}',
    metadata jsonb default '{}',
    created_at timestamp with time zone default now(),
    updated_at timestamp with time zone default now()
);

-- Gallery with categorization and metadata
CREATE TABLE IF NOT EXISTS public.gallery_items (
    id bigint primary key generated always as identity,
    title text not null,
    slug text unique not null,
    description text,
    image_url text not null,
    thumbnail_url text,
    blur_hash text,
    category text not null,
    subcategory text,
    is_premium boolean default false,
    required_tier user_tier default 'grassroot',
    coin_price integer default 0 check (coin_price >= 0),
    views integer default 0 check (views >= 0),
    likes integer default 0 check (likes >= 0),
    downloads integer default 0 check (downloads >= 0),
    is_featured boolean default false,
    is_published boolean default true,
    photographer text,
    location text,
    taken_at timestamp with time zone,
    camera_info jsonb default '{}',
    tags text[] default '{}',
    metadata jsonb default '{}',
    created_at timestamp with time zone default now(),
    updated_at timestamp with time zone default now()
);

-- Media content for additional content types
CREATE TABLE IF NOT EXISTS public.media_content (
    id bigint primary key generated always as identity,
    title text not null,
    slug text unique not null,
    description text,
    type content_type not null,
    file_url text not null,
    thumbnail_url text,
    blur_hash text,
    duration_seconds integer,
    file_size bigint,
    mime_type text,
    is_premium boolean default false,
    required_tier user_tier default 'grassroot',
    coin_price integer default 0 check (coin_price >= 0),
    view_count integer default 0 check (view_count >= 0),
    like_count integer default 0 check (like_count >= 0),
    download_count integer default 0 check (download_count >= 0),
    share_count integer default 0 check (share_count >= 0),
    is_featured boolean default false,
    is_published boolean default true,
    creator text,
    category text,
    subcategory text,
    explicit_content boolean default false,
    quality text,
    tags text[] default '{}',
    metadata jsonb default '{}',
    created_at timestamp with time zone default now(),
    updated_at timestamp with time zone default now()
);
